INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (1, 0, 99, N'../Assets/sportsbar1 .png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (2, 100, 199, N'../Assets/sportsdrik1.png' )
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (3, 200, 349, N'../Assets/sportsprotein1.png' )
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (4, 350, 549, N'../Assets/sportsbar2.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (5, 550, 799, N'../Assets/sportsdrik2.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (6, 800, 1099, N'../Assets/sportsbukser1.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (7, 1100, 1449, N'../Assets/sportsbar3.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (8, 1450, 1849, N'../Assets/sportsdrik3.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (9, 1850, 2299, N'../Assets/sportsprotein2.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (10, 2300, 2799, N'../Assets/sportsbar4.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (11, 2800, 3349, N'../Assets/sportsnack1.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (12, 3350, 3949, N'../Assets/sportsudstyr2.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (13, 3950, 4599,  N'../Assets/sportsudstyr3.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (14, 4600, 5299, N'../Assets/sportsprotein3.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (15, 5300, 6049, N'../Assets/sportsclothes1.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (16, 6050, 6849, N'../Assets/sportsudstyr4.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (17, 6850, 7699, N'../Assets/sportsdrik4.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (18, 7700, 8599, N'../Assets/sportsnack2.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (19, 8600, 9999, N'../Assets/sportstaske1.png')
INSERT INTO [dbo].[Levels] ([LevelValue], [MinXP], [MaxXP], [Gave]) VALUES (20, 10000, 100000, N'../Assets/sportsudstyr.png')
INSERT INTO [dbo].[Client] ( [Height], [Weight], [FatPercentage], [Age], [Gender], [WaistSize], [ArmSize], [Username], [FirstName], [LastName], [Password], [PhoneNumber], [TotalXP], [Image]) VALUES ( 181, CAST(75 AS Decimal(18, 0)), CAST(35 AS Decimal(18, 0)), 27, N'Mand', 120, CAST(33 AS Decimal(18, 0)), N'Gibbernakker', N'Konrad', N'Kirkebjerg', N'1', 11111111, 100, N'../Assets/Konrad.png')
INSERT INTO [dbo].[Client] ( [Height], [Weight], [FatPercentage], [Age], [Gender], [WaistSize], [ArmSize], [Username], [FirstName], [LastName], [Password], [PhoneNumber], [TotalXP], [Image]) VALUES ( 178, CAST(78 AS Decimal(18, 0)), CAST(22 AS Decimal(18, 0)), 24, N'Mand', 120, CAST(47 AS Decimal(18, 0)), N'oli', N'Oliver', N'Eierstrand', N'oli', 12345678, 4000, N'../Assets/Oliver.png')
INSERT INTO [dbo].[Client] ( [Height], [Weight], [FatPercentage], [Age], [Gender], [WaistSize], [ArmSize], [Username], [FirstName], [LastName], [Password], [PhoneNumber], [TotalXP], [Image]) VALUES ( 170, CAST(68 AS Decimal(18, 0)), CAST(25 AS Decimal(18, 0)), 30, N'Mand', 120, CAST(10 AS Decimal(18, 0)), N'Ojay', N'Omar', N'Jaber', N'3333', 87654321, 2000, N'../Assets/Omar.png')
INSERT INTO [dbo].[Client] ( [Height], [Weight], [FatPercentage], [Age], [Gender], [WaistSize], [ArmSize], [Username], [FirstName], [LastName], [Password], [PhoneNumber], [TotalXP], [Image]) VALUES ( 165, CAST(79 AS Decimal(18, 0)), CAST(30 AS Decimal(18, 0)), 36, N'Kvinde', 120, CAST(9 AS Decimal(18, 0)), N'Talus', N'Talia', N'Damary', N'4444', 15612733, 7705, N'../Assets/Talia.png')
INSERT INTO [dbo].[Client] ( [Height], [Weight], [FatPercentage], [Age], [Gender], [WaistSize], [ArmSize], [Username], [FirstName], [LastName], [Password], [PhoneNumber], [TotalXP], [Image]) VALUES ( 166, CAST(99 AS Decimal(18, 0)), CAST(31 AS Decimal(18, 0)), 41, N'Mand', 120, CAST(40 AS Decimal(18, 0)), N'censor', N'Censor', N'Censorsen', N'censor', 12378913, 495, N'../Assets/Mand5.png')
INSERT INTO [dbo].[Client] ( [Height], [Weight], [FatPercentage], [Age], [Gender], [WaistSize], [ArmSize], [Username], [FirstName], [LastName], [Password], [PhoneNumber], [TotalXP], [Image]) VALUES ( 159, CAST(58 AS Decimal(18, 0)), CAST(29 AS Decimal(18, 0)), 26, N'Kvinde', 120, CAST(57 AS Decimal(18, 0)), N'ILoveTv', N'Julie', N'Hassan', N'6666', 77771273, 4685, N'../Assets/Kvinde2.png')
INSERT INTO [dbo].[Client] ( [Height], [Weight], [FatPercentage], [Age], [Gender], [WaistSize], [ArmSize], [Username], [FirstName], [LastName], [Password], [PhoneNumber], [TotalXP], [Image]) VALUES ( 159, CAST(58 AS Decimal(18, 0)), CAST(19 AS Decimal(18, 0)), 46, N'Mand', 180, CAST(57 AS Decimal(18, 0)), N'Best', N'Alfred', N'Pedersen', N'7777', 74271293, 10800, NULL)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Armbøjninger', 25)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Dødløft', 75)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Lunges', 65)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Bænkpres', 55)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Rows', 35)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Løb 1 km', 10)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Løb 2 km', 20)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Løb 5 km', 50)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Løb 7 km', 75)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Løb 10 km', 100)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Løb 15 km', 150)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Løb 20 km', 200)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Biceps', 50)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Skulderpres', 55)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Chinups', 50)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Dumbell Curls', 35)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Shoulder Shugs', 30)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Tricep Pushdown', 60)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Mavebøjninger', 25)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Planke', 25)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Squats', 75)
INSERT INTO [dbo].[Exercises] ([ExerciseName], [XpForExercise]) VALUES (N'Ingen øvelse', 0)
INSERT INTO [dbo].[Trainer] ([FirstName], [LastName],[Password],[PhoneNumber],[Username],[YearsOfExpericence], [Image]) VALUES ('Trainer', 'Trainersen', 'admin', 12345678, 'admin',5,'../Assets/Trainer.png')
