// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleDB
{
    public partial class ClientTraining
    {
        public int ExerciseId { get; set; }
        public string TrainingType { get; set; }
    }
}