// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleDB
{
    public partial class Client
    {
        public int Id { get; set; }
        public decimal Weight { get; set; }
        public string Gender { get; set; }
        public decimal FatPercent { get; set; }
        public int ClientXp { get; set; }
        public int ClientLevel { get; set; }
        public int Height { get; set; }
    }
}