// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleDB
{
    public partial class ClientAppointment
    {
        public int Id { get; set; }
        public string ClientAppointment1 { get; set; }
        public string Exercise { get; set; }
    }
}