// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleDB
{
    public partial class LevelUp
    {
        public int Id { get; set; }
        public string GoalName { get; set; }
        public decimal? XpEarned { get; set; }
    }
}