// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleDB
{
    public partial class TrainingExercise
    {
        public int Id { get; set; }
        public int? Squat { get; set; }
        public int? Run { get; set; }
        public int? SitUps { get; set; }
        public int? Planking { get; set; }
        public int? PushUps { get; set; }
        public int? BicepsCurts { get; set; }
        public int? TricepsPushdowns { get; set; }
    }
}