// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleDB
{
    public partial class TrainingLevel
    {
        public int TrainingId { get; set; }
        public decimal? XpearnedByExercise { get; set; }
    }
}