// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Console.db
{
    public partial class AchievementGift
    {
        public int Id { get; set; }
        public string GiftItem { get; set; }
        public decimal? Price { get; set; }
        public decimal? DiscountPercentage { get; set; }
        public int? ItemsInInventory { get; set; }
    }
}